#!/bin/bash

# These commands are run by supervisor to start workers for handling websockets

NAME="GraphSpace daphne workers"
GRAPHSPACE="/home/melvin/Documents/GSoC/GraphSpace"

set -e  # exit on error
cd $GRAPHSPACE
. venv/bin/activate
exec python manage.py runworker --only-channels=websocket.*