#!/bin/bash

NAME="GraphSpace daphne workers"
GRAPHSPACE="/home/melvin/Documents/GSoC/GraphSpace"

set -e  # exit on error
cd $GRAPHSPACE
. venv/bin/activate
exec python manage.py runworker --only-channels=websocket.*