name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, ready_for_review] # Runs when the someone opens a pull request

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Reviewer # Assigns Reviwer from reviewers list to the Pull Request  
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: '.github/auto_assign.yml' # Only needed if you use something other than .github/auto_assign.yml