name: Docker Build Frontend

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: login to docker hub 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set outputs
      id: vars
      if: ${{ github.ref == 'refs/heads/master' }}
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: create image
      run: docker build -t graphspace . 

    - name: push image 
      run: |
        docker tag graphspace maheshkasbe/graphspace:${{ steps.vars.outputs.sha_short }}
        docker tag graphspace maheshkasbe/graphspace:latest
        docker push maheshkasbe/graphspace:latest
        docker push maheshkasbe/graphspace:${{ steps.vars.outputs.sha_short }}