name: Labeling new issue
on:
  issues:
    types: ['opened','edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Label #Labels the issue by the description of the issue 
        uses: Renato66/auto-label@v2 
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          labels-synonyms: '{"bug":["error","need fix","not working"],"enhancement":["upgrade"],"question":["help"]}'
          labels-not-allowed: '["good first issue"]'