name: PR Labeler
on: pull_request_target # Runs when the someone creates a pull request

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-labeler:
    runs-on: ubuntu-latest

    steps:
      - name: branch-label # Labels the Pull Request by branch name as which branch the pr is raised to
        uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
      
      - name: size-label # Labels the Pull Request by the no of lines of code
        uses: "pascalgn/size-label-action@v0.4.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }